version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/:/go/src/sendable/api
    ports:
      - 443:443
      - 80:80
    networks:
      - vpc_local
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - ENV=${ENV}
  db:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - vpc_local
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  reacher:
    image: reacherhq/backend:latest
    environment:
      - RCH_WORKER_CONCURRENCY=10
    networks:
      - vpc_local
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/app/:/frontend/app
      - ./frontend/public/:/frontend/public
      - ./frontend/package.json/:/frontend/package.json
      - ./frontend/tailwind.config.ts/:/frontend/tailwind.config.ts
      - frontend_node_modules:/frontend/node_modules
    ports:
      - 3000:5173
    networks:
      - vpc_local
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  frontend_node_modules:
networks:
  vpc_local:
    driver: overlay
