version: '3.8'
services:
  api:
    depends_on:
      - db
      - reacher
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/:/go/src/email-validator/api
    environment:
      - env=DEV
    ports:
      - 443:443
      - 80:80
    networks:
      - vpc_local
  db:
    build:
      context: ./migrations
      dockerfile: Dockerfile.dev.db
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - vpc_local
  reacher:
    # depends_on:
    #   - rabbitmq
    image: reacherhq/backend:latest
    environment:
      - RCH_WORKER_CONCURRENCY=10
      # - RCH_AMQP_ADDR=amqp://localhost
      # - RCH_AMQP_ADDR=amqp://rabbitmq:5672
    networks:
      - vpc_local
  # rabbitmq:
  #   image: rabbitmq:3.12-management
  # clamav:
  #   image: clamav/clamav:1.3.0-41
networks:
  vpc_local:
    driver: bridge