entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

http:
  routers:
    frontend-router:
      rule: "PathPrefix(`/`)"
      service: frontend-service

    api-router:
      rule: "PathPrefix(`/api`)"
      service: api-service

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

    api-service:
      loadBalancer:
        servers:
          - url: "http://api"
