version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/go/src/email-validator/api
    environment:
      - env=DEV
  # add reacher service